### ISSUE TITLE
in 1.9b7 and 1.9b8: impossible to open Nagvis context menu on any line

### ISSUE THREAD

**Issue by PepeOnAChair** [NagVis/nagvis#66] opened 2016-08-26 06:41 UTC
Hello,
in 1.9b7 and 1.9b8: impossible to open Nagvis context menu on any line. In 1.9b6 I can open context menu at least on some lines. On others I can open it, but before I can open it, I have to move one or both ends of the line to a different possition. Some layers related problem?
Pep.

**Comment by LarsMichelsen** [comment] 2016-08-27 07:33
Hi Pepe,

is this a duplicate of #65 or a different issue? I can open the context menus in all cases I tried. Do you have an example config?

**Comment by PepeOnAChair** [comment] 2016-09-26 18:55
Hello,
yes. It might by a duplicate problem, so you can close this.
Pepa

**Closed** 2016-09-27 18:31 UTC
