### ISSUE TITLE
500 error with check_mk/omd

### ISSUE THREAD

**Issue by dgcurtis** [NagVis/nagvis#105] opened 2017-05-02 19:25 UTC
Both 1.9b15 and 1.9b16 are producing 500 errors when installed on omd.   I use check_mk version 1.2.8p20.

Here is the error generated in the logs:

`[Tue May 02 15:20:32.618893 2017] [fcgid:warn] [pid 28342] [client 127.0.0.1:37216] mod_fcgid: stderr: PHP Parse error:  syntax error, unexpected '.', expecting ')' in /opt/omd/sites/csrdev/local/share/nagvis/htdocs/server/core/classes/CorePDOHandler.php on line 54`

Downgrading to 1.9p14 causes the site to work again.

**Comment by LarsMichelsen** [comment] 2017-05-03 09:08
The issue has already been fixed with commit cafd9e0881cc9401c870b1d586051395bd4c90a4. Could you pleas etry to apply the change manually to your installation to confirm that the issue is fixed?

**Comment by dgcurtis** [comment] 2017-05-03 12:52
I checked out that commit and it works now.  Thanks!

**Comment by LarsMichelsen** [comment] 2017-05-04 16:12
Thanks! The fix release has been published

**Closed by LarsMichelsen** 2017-05-04 16:12 UTC
