### ISSUE TITLE
1.9b10 - Labels move to position 0,0 on update

### ISSUE THREAD

**Issue by akp982** [NagVis/nagvis#81] opened 2016-11-22 04:43 UTC
I updated to 1.9b10 to resolve the issue I was having with the status in the hover menu not refreshing, while that works well whenever there is an update to an object the label for that object moves to position 0,0, when I refresh the page it goes back to where it should be, only to then move about 10/15 seconds later when it updates.

This happened with icons and lines.

The position for these the config is
label_x=+24
label_y=+4

I have tested in Chrome and IE on Windows10 with the same effect.

Screenshots below encase I didn't describe it right.

I have looked though the issue log and the changelog but can't seem to see anything about this at the moment.

Thanks
Andy

![image](https://cloud.githubusercontent.com/assets/2547490/20511244/64bf0c78-b06e-11e6-8343-867527dd091f.png)

![image](https://cloud.githubusercontent.com/assets/2547490/20511162/beca159c-b06d-11e6-9cd7-3261e5da56a2.png)

BTW - Thanks for all the awesome work you do on this and for making such a useful tool :-D 👍

**Comment by akp982** [comment] 2016-11-23 04:05
Note: Downgraded to 1.9b and applied the 4 files from the fix for the hover menu not updating (the reason I updated in the first place) from https://github.com/NagVis/nagvis/commit/e1d8028225b1e81041d05c96c61c9484b08125e5 and all appears to be working OK

I don't know my way around js / GitHub enough to work out why the labels would be moving on b10 but the above work around works for me for the moment :)

**Comment by skydiver123** [comment] 2016-11-30 13:04
Facing the same issue with Version 1.9.b10 
Thank you too for this awesome work!

**Comment by LarsMichelsen** [comment] 2016-11-30 19:09
I tried to reproduce this issue with Chrome and Firefox and was not able to.

Some questions:

- Did you also try Firefox?
- Do you mean the labels are repositioned on regular object updates or state change?
- Are only line labels affected?
- Or labels of a specific object type?

**Comment by miken32** [comment] 2016-12-01 00:23
It appears to be related to commit 2a5f0a4d58886677d75983dd9e7c4849df77494b which removed `this.place()` from `ElementLabel.render()`. By replacing that line, I can get it to keep the labels _mostly_ in the right place – there is some shifting still.

I experience this only on icon labels (my map only has weathermap lines and host icons.) It's not related to state change, and I use Firefox.

**Comment by LarsMichelsen** [comment] 2016-12-01 20:06
Yeah, looks like. I was already thinking about this commit, but till now I was not able to reproduce the issue. Maybe there is some detail in you map config that is different over here.

Can you post / send me the config file?

**Comment by miken32** [comment] 2016-12-01 20:41
Sure, here it is:

```
define global {
alias=NOC Connectivity
grid_show=0
backend_id=live_1
iconset=std_big
label_show=1
object_id=f43362
recognize_services=0
hover_childs_show=0
line_type=15
label_style=font-weight:bold;background-color:#00ffee33;padding:2px
label_background=transparent
background_color=transparent
label_border=transparent
}

define shape {
icon=demo_traffic_load_legend.png
x=787
y=246
object_id=507890
}

define host {
host_name=aci1
x=320
y=32
object_id=33844f
}

define host {
host_name=aci2
x=448
y=32
object_id=9fe10b
}

define host {
host_name=asa1
x=320
y=544
object_id=1c8fb2
}

define host {
host_name=asa2
x=448
y=544
object_id=848f32
}

define host {
host_name=switch1
x=96
y=288
object_id=1da680
label_x=-52
label_y=+10
}

define host {
host_name=switch2
x=672
y=288
object_id=4a7007
label_x=+36
label_y=+10
}

define host {
host_name=esx1
x=384
y=160
object_id=e94125
}

define host {
host_name=esx2
x=384
y=416
object_id=864d97
}

define service {
host_name=switch2
service_description=snmp-interface-44
x=4a7007%+32,4a7007%+64,9fe10b%+32
y=4a7007,4a7007%-192,9fe10b%+32
object_id=f1edc1
view_type=line
label_show=0
}

define service {
host_name=switch2
service_description=snmp-interface-47
x=4a7007%+0,4a7007%+0,848f32%+32
y=4a7007%+32,4a7007%+224,848f32
object_id=5f28b8
view_type=line
label_show=0
}

define service {
host_name=switch1
service_description=snmp-interface-44
x=1da680,1da680%-64,33844f
y=1da680,1da680%-192,33844f%+32
object_id=93035f
view_type=line
label_show=0
}

define service {
host_name=switch1
service_description=snmp-interface-47
x=1da680%+32,1da680%+32,1c8fb2
y=1da680%+32,1da680%+224,1c8fb2
object_id=884904
view_type=line
label_show=0
}

define service {
host_name=switch1
service_description=snmp-interface-13
x=1da680%+32,e94125%+0
y=1da680%+0,e94125%+32
object_id=e4d915
view_type=line
label_show=0
}

define service {
host_name=switch1
service_description=snmp-interface-14
x=1da680%+32,864d97%+0
y=1da680%+32,864d97%+0
object_id=1852cf
view_type=line
label_show=0
}

define service {
host_name=switch2
service_description=snmp-interface-13
x=4a7007%+0,e94125%+32
y=4a7007%+0,e94125%+32
object_id=bbb53d
view_type=line
label_show=0
}

define service {
host_name=switch2
service_description=snmp-interface-14
x=4a7007%+0,864d97%+32
y=4a7007%+32,864d97%+0
object_id=961487
view_type=line
label_show=0
}

define service {
host_name=switch1
service_description=snmp-interface-Po1
x=1da680%+32,4a7007%+0
y=1da680%+16,4a7007%+16
object_id=53c4d9
view_type=line
label_show=0
}

define service {
host_name=switch1
service_description=snmp-interface-25
x=1da680%+32,1da680%+64,e94125%+0
y=1da680,1da680%-128,e94125%+0
object_id=5e2f16
view_type=line
label_show=0
}

define service {
host_name=switch1
service_description=snmp-interface-26
x=1da680%+32,1da680%+128,864d97%+0
y=1da680%+32,1da680%+160,864d97%+32
object_id=9bd25a
view_type=line
label_show=0
}

define service {
host_name=switch2
service_description=snmp-interface-25
x=4a7007%+0,4a7007%-32,e94125%+32
y=4a7007%+0,4a7007%-128,e94125%+0
object_id=7e571a
view_type=line
label_show=0
}

define service {
host_name=switch2
service_description=snmp-interface-26
x=4a7007%+0,4a7007%-96,864d97%+32
y=4a7007%+32,4a7007%+160,864d97%+32
object_id=d9e29b
view_type=line
label_show=0
}

define service {
host_name=switch1
service_description=snmp-interface-47
x=1da680%+0,1da680%+0,1c8fb2%+0
y=1da680%+32,1da680%+282,1c8fb2%+32
object_id=f729e3
view_type=line
label_show=0
}

define service {
host_name=switch2
service_description=snmp-interface-47
x=4a7007%+32,4a7007%+32,848f32%+32
y=4a7007%+32,4a7007%+280,848f32%+32
object_id=1680ac
view_type=line
label_show=0
}
```

**Comment by skydiver123** [comment] 2016-12-14 14:11
Did somebody found a Workaround?
I tried to replace the this.place() in ElementLabel.render(), but the labels still move to 0,0 with Firefox and Chrome.

**Comment by LarsMichelsen** [comment] 2016-12-14 21:42
I had a deep look into the code and found that for icons, since some versions the labels are positioned after the icon image is loaded. This is done to ensure that the relative label positions respect the final size of the object icons. The mechanic is simply using the "onload" event of the icons <img> object.

In case the onload event is not fired (for whatever reason) the labels will not be positioned. So this is the first idea to follow. 

One reason might be that the image is already cached in the browser or something like this. Don't know exactly. Could you try to disable the browser cache or at least empty it and then open up the map again to see whether or not this changes anything?

The second one: Do you use the NagVis map zoom or do you always view the maps at 100% zoom?

**Comment by akp982** [comment] 2016-12-15 09:08
@skydiver123 - Downgrading to 1.9b was the work around for me

**Comment by akp982** [comment] 2016-12-15 09:10
@LarsMichelsen there was no change to my browser when using b10 vs b9, if this was a cache issue I'd have expected it still to be the case on b9? 

I have however just popping b10 back on and clearing my cache it still has the same effect that labels are moved to 0,0 when objects are refreshed

I don't use map zoom its kept at 100%

**Comment by LarsMichelsen** [comment] 2016-12-20 20:18
Please check out the next nightly build. Maybe I found a solution. But since I was not able to produce the issue before, I can not confirm the fix on my own.

**Comment by skydiver123** [comment] 2016-12-22 15:58
@LarsMichelsen Thank you for your work. 
Unfortunately same issue... 
I tried to set up a different map, even the same - labels are moving to 0,0.

![image](https://cloud.githubusercontent.com/assets/2011202/21431498/cec26618-c867-11e6-8ae4-cce0c7a53869.png)

**Closed** 2016-12-25 11:18 UTC

**Comment by LarsMichelsen** [comment] 2016-12-25 11:20
I just re-added the this.place() call to the ElementLabel.render() method since this seems to solve your issues. Please let me know whether or not the issue is gone.

**Comment by Alex85651** [comment] 2017-02-17 09:44
Hi,
I got a similar issue on the 1.9b11 version. The label is moving 10 pixels on the right after update.
Does anyone have the same problem ?

**Comment by Links2004** [comment] 2017-03-08 16:09
can confirm this with 1.9b13, after a update all labels move to the right.

**Comment by LarsMichelsen** [comment] 2017-03-11 10:04
I have now tried to reproduce this for a long time. Things I discovered:

a) A problem occurred on state update when only the output or perfdata changed (not the state). I now tried a different fix. I moved the .place() call after the .draw() call within ElementLabel.updateAttrs(). The advantage is that there is no need to pipe the "w" through all the functions.

b) A problem occurred on state change between any regular state and any stale state when using the std_medium iconset on icon objects. The stale icon images had a wrong size. I replaced these images now.

Please check out the upcoming daily build. On confirmed fix I'll publish the next release.

**Comment by dgcurtis** [comment] 2017-05-04 15:39
I think this is still an issue with gadgets.  I am using check_mk (omd) with nagvis 1.9b14 and I am having this issue only with gadgets.  Icons and lines labels are working normal.
