### ISSUE TITLE
Personalize line_type perfdata input

### ISSUE THREAD

**Issue by emirjonb** [NagVis/nagvis#149] opened 2018-03-22 14:54 UTC
Is possible to personalize the order input of perfdata on Nagvis?
I'm trying to adapt a bulk of snmp scripts to Nagvis maps but it's hard to change every single of them.
I've changed one script to build the pefdata in the following order: `| nagvis_inL=4.1% nagvis_outL=12.5% nagvis_inT=4Mbps nagvis_outT=12Mbps traffic_in=4080634,3Bits/s;70000000;90000000;0;100000000 traffic_out=12479442,5Bits/s;70000000;90000000;0;10000000`
 and get the desired output. 
![ok](https://user-images.githubusercontent.com/14164077/37777501-fed1cf10-2de7-11e8-93fd-ae9cf5fa869e.PNG)

Can we personalize the order of input (create another case on lines.js) like 
`case '15':   // -%+BW-><-%+BW- lines `; that the user can specify `isset(perfdata[0][1])` location with the desired order depending on personalized perl scripts used. This specific scripts generate a specific order Load IN, traffic IN, ...IN ; and then Load OUT , Traffic OUT , ..OUT  [in short the order is all IN and than all OUT variables]
![nagvisi](https://user-images.githubusercontent.com/14164077/37777666-6a32fcb6-2de8-11e8-8e12-7f8438723e0e.PNG)
Which is the best/fast way to do this changes since JS is much more flexible than the snmp crawler perl scripts :),  It would be better if Nagvis were a little more flexible on perfdata input.

**Comment by LarsMichelsen** [comment] 2018-03-24 15:52
Some kind of duplicate of #121.  Have a look at share/frontend/nagvis-js/js/ElementLine.js parsePerfdata().

**Closed by LarsMichelsen** 2018-03-24 15:52 UTC

**Comment by prohand** [comment] 2018-07-24 09:03
Hello

I am using the plugin check_centreon_snmp_traffic I modified the following line:

printf("|traffic_in=".$in_perfparse_traffic_str."Bits/s;$warningBit;$criticalBit;0;$speed_card traffic_out=".$out_perfparse_traffic_str."Bits/s;$warningBit;$criticalBit;0;$speed_card\n");

By :

printf("|load_In=".$in_usage."%%;$warningBit;$criticalBit;0;0 load_Out=".$out_usage."%%;$warningBit;$criticalBit;0;0 traffic_In=%.2f".$in_prefix."b;".$warningBit.";".$criticalBit.";0;0 traffic_Out=%.2f".$out_prefix."b;".$warningBit.";".$criticalBit.";0;0 traffic_in=".$in_perfparse_traffic_str."Bits/s;$warningBit;$criticalBit;0;$speed_card traffic_out=".$out_perfparse_traffic_str."Bits/s;$warningBit;$criticalBit;0;$speed_card \n",$in_traffic,$out_traffic);

The problem is solved.
