### ISSUE TITLE
Loading... on top, that never finishes

### ISSUE THREAD

**Issue by gmourani** [NagVis/nagvis#160] opened 2018-07-10 18:17 UTC
Hello,

nagvis = 1.9.8
centos = 6.9
apache = 2.2.34
php = 5.6.33
No error message or javascript in the web server log file or browser.
Same problem on all browser

When I start Nagvis, it shows a "Loading..." on top, but never finishes with the task.

Regards,

**Comment by T100D** [comment] 2018-07-15 12:40
I run a busy server, and sometimes a nagvis map update clears the file.
Are your map files in /usr/loca//nagvis/etc/maps alright?

**Comment by gmourani** [comment] 2018-07-16 12:52
Yes, but I think I found something with MK Livestatus. Seem that it's not working as expected and this make Nagvis not to display the map. I've to make more tests on this.

**Comment by T100D** [comment] 2018-07-16 13:20
This is in our /usr/local/nagvis/etc/nagvis.ini.php file

```
[backend_live_1]
  backendtype="mklivestatus"
  socket="unix:/usr/local/nagios/var/rw/live"
```
The live folder has special permission on it.

`  drwxrwsr-x. 2 nagios nagcmd     4096 Jul 16 13:12 rw`

**Comment by wernerfred** [comment] 2018-07-26 14:47
We had the same issue but we figured out that if you zoom in or out with your mouse wheel it immediately loads the map and shows all points.
Maybe this info helps the devs in finding the problem causing lines of code or you as a workaround for your endless loading maps.

**Comment by wernerfred** [comment] 2018-09-10 17:17
Since using this changes: https://github.com/NagVis/nagvis/issues/162 the problem is gone at our installation

**Comment by LarsMichelsen** [comment] 2019-06-01 23:10
Should be fixed.

**Closed by LarsMichelsen** 2019-06-01 23:10 UTC
