### ISSUE TITLE
Cannot manage Users/Roles since version 1.9b15

### ISSUE THREAD

**Issue by alien8r** [NagVis/nagvis#110] opened 2017-05-09 14:29 UTC
Our RHEL6 boxes running the latest NagiosXI have PHP Version 5.3.3, Apache/2.2.15, mysql 14.14, and use NagVis LogonMixed, CoreAuthModSQLite, CoreAuthorisationModSQLite.
The fixes in version 1.9b18 let us log in and manage/edit maps.
Any attempt to work on Users or Roles does nothing, no error messages anywhere. 
The interface eventually returns saying a user or role was added/updated/deleted but no such action happened.
No errors at all in /var/log or /var/log/http.

**Comment by LarsMichelsen** [comment] 2017-05-09 17:44
Works for me with 1.9b18 and PHP 5.3.29. Can you please send me the information found on the "NagVis support information" page?

**Comment by alien8r** [comment] 2017-05-09 17:53
The one I reverted back to 1.9b14 immediately allowed user/role edits again.
The one I left at 1.9b18 is listed below:
---------------
NagVis Version	1.9b18
PHP Version	5.3.3
MySQL Version	mysql Ver 14.14 Distrib 5.1.73, for redhat-linux-gnu (x86_64) using readline 5.1
OS	Linux xxxx.edu 2.6.32-504.23.4.el6.x86_64 #1 SMP Fri May 29 10:16:43 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux
Webserver Information
SERVER_SOFTWARE	Apache/2.2.15 (Red Hat)
SCRIPT_FILENAME	/usr/local/nagvis/share/frontend/nagvis-js/index.php
SCRIPT_NAME	/nagvis/frontend/nagvis-js/index.php
REQUEST_TIME	1494352104 (gmdate(): Tue, 09 May 2017 17:48:24 +0000)
PHP Information
error_reporting	32767
safe_mode	no
max_execution_time	30 seconds
memory_limit	128M
loaded modules	Core, date, ereg, libxml, openssl, pcre, zlib, bz2, calendar, ctype, hash, filter, ftp, gettext, gmp, SPL, iconv, Reflection, session, standard, shmop, SimpleXML, sockets, exif, tokenizer, xml, apache2handler, curl, dom, fileinfo, gd, json, ldap, mbstring, mcrypt, mssql, mysql, mysqli, PDO, pdo_dblib, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, snmp, SourceGuardian, sqlite3, ssh2, wddx, xmlreader, xmlwriter, xsl, zip
json_encode	Yes
json_decode	Yes
Client Information
USER_AGENT	Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:53.0) Gecko/20100101 Firefox/53.0
Logon Information
Logon Module	LogonMixed
Auth Module	CoreAuthModSQLite
Authorization Module	CoreAuthorisationModSQLite
Logon Var	REMOTE_USER
REMOTE_USER	
Logon Create User?	0
Logon Create User Role?	Guests
Current User Information
User Logged In	xxxx (3)
User Auth Module	CoreAuthModSQLite
User Logon Module	LogonMixed
User Trusted Auth	No
User Roles	[{"roleId":"1","name":"Administrators"}]
User Permissions	{"*":{"*":{"*":[]}}}

**Comment by alien8r** [comment] 2017-05-10 17:09
Finally got an error message to popup when trying to modify a user:
Invalid JSON response
 URL: /nagvis/server/core/ajax_handler.php?mod=UserMgmt&act=view&_ajaxid=1494435870
Response:
Could not execute the -create-auth-users query: HY000( 1): table users already exists

**Comment by LarsMichelsen** [comment] 2017-05-10 17:19
Interesting detail. Could you also possibly send me the auth.db file?

**Comment by alien8r** [comment] 2017-05-10 18:13
I had to remove some user/passwd first, sorry.
[auth_COPY.zip](https://github.com/NagVis/nagvis/files/990806/auth_COPY.zip)

**Comment by alien8r** [comment] 2017-05-11 16:47
I deleted the previous comment that had the auth.db file in it as I could not see any other way to get that file out of public view.

**Comment by LarsMichelsen** [comment] 2017-05-14 19:11
I already downloaded the file you previously downloaded. The only interesting was that the password hashes of the users were set to an empty string. I added my own hash by hand and was able to authenticate. Then I was able to do all the user actions with 1.9b19 with PHP 5.3

The error message you mentioned:

> Could not execute the -create-auth-users query: HY000( 1): table users already exists

This should only occur when the table did not exist before. Did you possibly delete the tables or the whole sqlite file? Maybe it is some kind of race condition where two processes try to initialize the SQLite database.

**Comment by alien8r** [comment] 2017-05-15 11:17
By testing on my other server the issue is cleared simply by reverting to version 1.9b14.

**Comment by alien8r** [comment] 2017-05-17 17:22
I just applied the nagvis-1.9b14 update script to the server that I had left at 1.9b18 which was the source of the auth.db file you looked at.
Simply running nagvis-1.9b14 with the default options returned all functionality and got rid of all the slowness/timeouts.
I can now add/delete/modify users and roles again. 
Again, the only thing done was to untar nagvis-1.9b14.tar.gz and run  ./install.sh.

**Comment by LarsMichelsen** [comment] 2017-05-17 20:22
I understood you can fix it by downgrading, but that does not help at all tracking down the issue. There have been a huge amount of changes between both versions.

**Comment by alien8r** [comment] 2017-05-18 15:23
Loaded the nightly build:
Timeouts on loading any page are gone, performance seemed normal.
Cannot manage users or roles: after it finally times out user changes get a false "completed" message.
Renaming a map results it renaming of that maps cfg file and a long wait as some function times out.  That map name errors when you try to open it. Renaming said map to the original name happens quickly and restores it to usability.
Cannot change own password, eventually returns with proper error message.

**Comment by LarsMichelsen** [comment] 2017-05-21 17:20
I just installed a fresh CentOS 6.9 system with minimal system and was able to reproduce the issue. 
Seems the SQLite resources were not cleaned up automatically which left the DB connection open until some timeout occured. This resulted in "hanging" actions with older SQLite versions.

I have just pushed a fix.

**Comment by LarsMichelsen** [comment] 2017-05-21 17:21
Please check out the next nightly build to verify the solution.

**Closed** 2017-05-21 17:21 UTC

**Comment by alien8r** [comment] 2017-05-22 13:37
I loaded your 1.9b19 build.
Have only tested the "modify user" functions so far and it was worked perfectly!

**Comment by alien8r** [comment] 2017-05-22 15:51
I loaded your nightly build labeled 1.9b20.
Preliminary testing also good.

**Comment by alien8r** [comment] 2017-05-25 19:44
I usually let Nagvis take me to NagiosXI before running a command, that's where I 'm used to working.
Tried using the right-click options (Downtime,/Reschedule/Acknowledge) but they fail with "requested URL /nagiosxi/includes/components/xicore/cmd.cgi was not found ".
Default NagiosXI installation results in "/opt/nagios/sbin/cmd.cgi"
I'm guessing I would have to manualle edit GlobalMainCfg.php.

**Comment by alien8r** [comment] 2017-05-25 20:13
Okay, with default paths use don NagiosXI (current version is 5.4.4) the http path to cmd.cgi is actually "/nagios/sbin/cmd.cgi"  rather than under /nagiosxi.

**Comment by alien8r** [comment] 2017-05-26 14:29
Possible fix>
Change command to use status.cgi rather than cmd.cgi.
Example: host_downtime_url="[html_cgi]/status.cgi?cmd_typ=55&host=[name]"
