### ISSUE TITLE
Map rotation with alert trigger (autojump to alert)

### ISSUE THREAD

**Issue by LMS235** [NagVis/nagvis#292] opened 2021-09-23 06:03 UTC
Hello, 

Is there a possibility to jump automatically to the MAP with an event (e.g. alert) during the map rotation?

Example: A map rotation of 10 maps, the rotation is currently at map 3 and on map 7 an alert is displayed, the rotation then immediately jumps to map 7, after the alert it continues normally in the rotation.

Otherwise you would have to wait until map 7 is reached to see the alert.

Because that's exactly what we would need on monitoring TVs without the possibility of manual intervention.
Either in the standard or with manual code adaptations.

I think something like this is also described here - https://github.com/NagVis/nagvis/issues/285

Regards

**Comment by LarsMichelsen** [comment] 2021-11-26 20:06
Yes, would be cool to have. I am closing this as a duplicate of #285.

**Closed by LarsMichelsen** 2021-11-26 20:06 UTC
