### ISSUE TITLE
Multiples distincts geographical maps ?

### ISSUE THREAD

**Issue by mathieuchateau** [NagVis/nagvis#169] opened 2018-09-19 12:55 UTC
Hello,
I need multiple geographical interactive maps. 
Once one is created, all objects also appears on the other map.

How to have each map with its own objects ?

Using nagvis 1.9.3, sources=worldmap

Regards,

**Comment by LarsMichelsen** [comment] 2019-06-01 23:15
Sorry, it's not planned at the moment. Should not be too hard to realize by linking different worldmaps  to independent worldmap.db files. But I currently have no plan to realize this.

**Comment by LarsMichelsen** [comment] 2019-06-01 23:36
Closing this one. It's a duplicate of #139

**Closed by LarsMichelsen** 2019-06-01 23:36 UTC
Labels: enhancement, help wanted
