### ISSUE TITLE
impossible to open Nagvis context menu on line

### ISSUE THREAD

**Issue by PepeOnAChair** [NagVis/nagvis#65] opened 2016-08-26 06:40 UTC
Hello,
in 1.9b6, 1.9b7 and 1.9b8 (nighty): impossible to open Nagvis context menu on line (host and service line) and staleless line in case when map is scrolled down. So this bug will not appear on maps smaller then browser window.
Pep.

**Comment by LarsMichelsen** [comment] 2016-08-27 07:33
Can reproduce it in scrolled situation. Will take a look at this.

**Comment by LarsMichelsen** [comment] 2016-08-27 07:47
Just pushed a fix to the git. Please check out next nightly git whether or not the problem is gone for you.

**Closed by LarsMichelsen** 2016-08-27 07:47 UTC

**Comment by amprantino** [comment] 2016-09-22 06:54
I face the same issue on version 1.9.b8. 
I have upgraded from 1.6 to 1.9b8 and the lines menu doesn't open

When I resized the map, so the page doesn't scroll, it worked again

**Comment by LarsMichelsen** [comment] 2016-09-22 18:59
1.9b8 has been released before the fix. You can try the daily build from http://nagvis.org/downloads 

I am waiting for approval.

**Comment by PepeOnAChair** [comment] 2016-09-26 18:57
Hello,
I installed "nagvis-1.9-nightly.tar.gz" downloaded today and it seems to be OK. Thank a lot for making the fix.
Pepe

**Comment by amprantino** [comment] 2016-09-26 20:40
Yes, 1.9 nightly seems OK
