### ISSUE TITLE
Labels on gadgets move to position 0,0 on refresh

### ISSUE THREAD

**Issue by dgcurtis** [NagVis/nagvis#108] opened 2017-05-05 18:20 UTC
The ticket https://github.com/NagVis/nagvis/issues/81 seems to be related.

I am using check_mk (omd) with nagvis 1.9b14. The labels for any gadget are resetting to the position 0,0 when refreshed. Icons and lines labels are working normal.

**Comment by LarsMichelsen** [comment] 2017-05-29 19:58
Cannot reproduce. Which browser? js errors?

**Comment by dgcurtis** [comment] 2017-05-30 13:21
I've tried it in every browser latest browser on my Mac running Sierra (Chrome, Firefox, Safari).  I've had other people try it on Windows with the same results.

Here are the js errors that show up in Firefox:

window.controllers is deprecated. Do not use it for UA detection.  index.php
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/  NagVisCompressed.js:1938

**Comment by LarsMichelsen** [comment] 2017-06-03 11:27
I just pushed a fix for the label positioning of gadgets. I am not sure that it fixes your problem because I was only able to produce a wrong positioned label on initial rendering and not on update.

You could try the next nightly build.

**Closed by LarsMichelsen** 2017-06-03 11:27 UTC
Labels: help wanted

**Comment by dgcurtis** [comment] 2017-06-06 00:31
I checked out 21fe633 and it's working properly now.

Thanks!
