### ISSUE TITLE
Error with Icinga2 and empty Hostgroups

### ISSUE THREAD

**Issue by gitmopp** [NagVis/nagvis#95] opened 2017-03-16 08:11 UTC
The following is a sample output of an Icinga2 empty hostgroup (hostgroup without members).
```
GET hostsbygroup
Filter: groups >= Test Printer
Stats: has_been_checked = 0
Stats: state = 0
[...]
200          27
[[0,0,0,0,0,0,0,0,0,0,0,0]]
```
The Web interface shows when I hover of the Icon "ERROR" in blue color and Summary Output: "The Object Test Printer does not exist (hostgroup)".
The hostgroup exists, but it does not have any members.
From my point of view an empty hostgroup is not an ERROR.

**Comment by ibrewster** [comment] 2017-03-16 13:46
Nagvis has issues with icinga2 and host groups in general, in my experience. You'll get this error even if the host group DOES have members, particularly if you have more than one host group on a map. A workaround that worked for me is to instead add a "dynamic group" object, and put that filter (`Filter: groups >= Test Printer`) into it. I'm not sure if that will work with an empty host group, however.

**Comment by gitmopp** [comment] 2017-03-16 22:08
NagVis also has problems if a host is in more than one hostgroup. The problem is related to Icinga2 Livestatus. As you can see in the example below the Icinga 2 Livestatus only reports the other hostgroup and not the hostgroup from the Filter "My Test Group".
If the host of "My Test Group" is only in one hostgroup Livestatus will report the hostgroup "My Test Group". If it is in two hostgroups it will only report "My other Testhostgroup".
The same problem applys also to servicesbyhostgroup.
I' ll also create a ticket for Icinga2, because for me it looks like a Icinga2 bug.
```
GET hostsbygroup
Filter: groups >= My Test Group
Stats: has_been_checked = 0
Stats: state = 0
Stats: has_been_checked != 0
Stats: scheduled_downtime_depth = 0
Stats: staleness < 1.5
StatsAnd: 4
Stats: state = 0
Stats: has_been_checked != 0
Stats: scheduled_downtime_depth = 0
Stats: staleness >= 1.5
StatsAnd: 4
Stats: state = 0
Stats: has_been_checked != 0
Stats: scheduled_downtime_depth > 0
StatsAnd: 3
Stats: state = 1
Stats: acknowledged = 0
Stats: scheduled_downtime_depth = 0
Stats: staleness < 1.5
StatsAnd: 4
Stats: state = 1
Stats: acknowledged = 0
Stats: scheduled_downtime_depth = 0
Stats: staleness >= 1.5
StatsAnd: 4
Stats: state = 1
Stats: acknowledged = 1
StatsAnd: 2
Stats: state = 1
Stats: scheduled_downtime_depth > 0
StatsAnd: 2
Stats: state = 2
Stats: acknowledged = 0
Stats: scheduled_downtime_depth = 0
Stats: staleness < 1.5
StatsAnd: 4
Stats: state = 2
Stats: acknowledged = 0
Stats: scheduled_downtime_depth = 0
Stats: staleness >= 1.5
StatsAnd: 4
Stats: state = 2
Stats: acknowledged = 1
StatsAnd: 2
Stats: state = 2
Stats: scheduled_downtime_depth > 0
StatsAnd: 2
Columns: hostgroup_name hostgroup_alias
OutputFormat: json
KeepAlive: on
ResponseHeader: fixed16

200          77
[["My other Testhostgroup","My other Testhostgroup0,9,0,0,0,0,0,0,0,0,0,0]]
```

**Comment by gitmopp** [comment] 2017-03-17 07:21
Using the ndo2db backend with Icinga2 seems to work.

**Comment by LarsMichelsen** [comment] 2017-03-17 10:13
I am pretty sure this is caused by a bug in the Icinga 2 livestatus implementation. It exists for a longer time and no one is willing to fix this. So Livestatus does not seem to be an option with Icinga 2 anymore.

The long existing issue has been closed by them: https://github.com/Icinga/icinga2/issues/1970

I can not fix this within NagVis livestatus code. So I am closing this one, sorry.

**Closed by LarsMichelsen** 2017-03-17 10:13 UTC

**Comment by gitmopp** [comment] 2017-03-17 10:15
Yes, it is a Icinga2 bug and it should be fixed in Icinga2. But it seems like they are working on it this time: https://github.com/Icinga/icinga2/issues/5078

**Comment by LarsMichelsen** [comment] 2017-04-17 13:44
I don't think that anybody is working on it.
